use airlines;

#####################
###KPI 1
SELECT DAY_TYPE, SUM(TOTAL_FLIGHTS) AS TOTAL_FLIGHTS
FROM (
    SELECT
        DAY_OF_WEEK,
        CASE WHEN DAY_OF_WEEK IN (6, 7) THEN 'Weekend' ELSE 'Weekday' END AS DAY_TYPE,
        COUNT(*) AS TOTAL_FLIGHTS
    FROM flights
    GROUP BY DAY_OF_WEEK, DAY_TYPE
) AS subquery
GROUP BY DAY_TYPE
ORDER BY DAY_TYPE;

##################
#KPI 2
SELECT
    YEAR_,
    MONTH_,
    AIRLINE,
    COUNT(*) AS CANCELLED_FLIGHTS
FROM flights
WHERE AIRLINE = 'B6' AND DAY_ = 1 AND CANCELLED = 1
GROUP BY YEAR_, MONTH_, AIRLINE
ORDER BY YEAR_, MONTH_;

##################
#KPI 3
SELECT
    WEEK(DATE_ADD(DATE(CONCAT(f.YEAR_, '-', f.MONTH_, '-', f.DAY_)), INTERVAL (f.DAY_OF_WEEK - 1) DAY)) AS WEEK_NUMBER,
    a1.STATE,
    a1.CITY,
    f.AIRLINE,
    SUM(CASE WHEN f.DEPARTURE_DELAY <> -9999 THEN f.DEPARTURE_DELAY ELSE 0 END) AS TOTAL_DEPARTURE_DELAY,
    SUM(CASE WHEN f.ARRIVAL_DELAY <> -9999 THEN f.ARRIVAL_DELAY ELSE 0 END) AS TOTAL_ARRIVAL_DELAY
FROM flights f
JOIN airports a1 ON f.ORIGIN_AIRPORT = a1.IATA_CODE
JOIN airports a2 ON f.DESTINATION_AIRPORT = a2.IATA_CODE
GROUP BY WEEK_NUMBER, a1.STATE, a1.CITY, f.AIRLINE
HAVING TOTAL_DEPARTURE_DELAY <> 0 OR TOTAL_ARRIVAL_DELAY <> 0
ORDER BY WEEK_NUMBER, a1.STATE, a1.CITY;

###############
#KPI 4
SELECT
    AIRLINE,
    COUNT(*) AS NUM_FLIGHTS
FROM flights
WHERE (DEPARTURE_DELAY = 0 OR ARRIVAL_DELAY = 0) AND DISTANCE BETWEEN 2500 AND 3000
GROUP BY AIRLINE;


